entries/urls.py
## -*- coding: utf-8 -*-

#=====================================================
# @file  : urls.py
# @brief : URLリンク定義
#=====================================================

#--------- import ---------
from django.conf.urls.defaults import *
from models import Entry

#--------- query ---------
info_dict = { 'queryset':Entry.objects.all(), }

#--------- entries ---------
urlpatterns = patterns('',

    # 一覧
    ( r'^page/(?P<object_id>\d+)/$', 'entries.views.page_list' ),
    # 新規作成
    ( r'^create/$', 'entries.views.create_entry' ),

    # 詳細閲覧
    ( r'^detail/(?P<object_id>\d+)/$', 'django.views.generic.list_detail.object_detail', info_dict ),
    # 更新
    ( r'^update/(?P<object_id>\d+)/$', 'django.views.generic.create_update.update_object', {'model':Entry } ),
    # 削除
    ( r'^delete/(?P<object_id>\d+)/$', 'django.views.generic.create_update.delete_object',
         { 'model':Entry, 'post_delete_redirect':'/entries/' } ),
    # コメント
    (r'^comments/', include('django.contrib.comments.urls')),
)

src/entries/urls.py
## -*- coding: utf-8 -*-

#=====================================================
# @file  : urls.py
# @brief : URLリンク定義
#=====================================================

#--------- import ---------
from django.conf.urls.defaults import *
from src.entries.models import Entry

#--------- import ---------
views_path = 'src.entries.views'

#--------- query ---------
info_dict = { 'queryset':Entry.objects.all(), }

#--------- entries ---------
urlpatterns = patterns('',

    # 一覧
    ( r'^page/(?P<object_id>\d+)/$', views_path + '.page_list' ),
    # 新規作成
    ( r'^create/$', views_path + '.create_entry' ),
    # 詳細閲覧
    ( r'^detail/(?P<object_id>\d+)/$', 'django.views.generic.list_detail.object_detail', info_dict ),
    # 更新
    ( r'^update/(?P<object_id>\d+)/$', 'django.views.generic.create_update.update_object', {'model':Entry } ),
    # 削除
    ( r'^delete/(?P<object_id>\d+)/$', 'django.views.generic.create_update.delete_object',
         { 'model':Entry, 'post_delete_redirect':'/entries/' } ),
    # コメント
    (r'^comments/', include('django.contrib.comments.urls')),
)

urls.py
# -*- encoding: utf-8 -*-

#=====================================================
# @file  : urls.py
# @brief : URLリンク定義
#=====================================================

#--------- import ---------
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin

import os

#--------- admin ---------
admin.autodiscover() # 管理画面のため

urlpatterns = patterns('',
    # admin : http://127.0.0.1:8000/admin/
    ( r'^admin/', include( admin.site.urls ) ),
)

#--------- URL ---------
urlpatterns += patterns('',
    # top : http://127.0.0.1:8000/top/
    ( r'^top/$', include('src.top.urls') ),
    # polls : http://127.0.0.1:8000/polls/
    ( r'^polls/', include('src.polls.urls') ),
    # entries : http://127.0.0.1:8000/entries/
    ( r'^entries/', include('src.entries.urls') ),
    # account : http://127.0.0.1:8000/account/
    ( r'^account/', include('src.account.urls') ),
    # mypage : http://127.0.0.1:8000/mypage/
    ( r'^mypage/', include('src.mypage.urls') ),
    # twitter : http://127.0.0.1:8000/twitter/
    ( r'^twitter/', include('src.twitter.urls') ),
)

urlpatterns += patterns('',
    (r'^medias/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

#--------- CSS ---------
if settings.DEBUG:
    urlpatterns += patterns('',
        ( r'^static/(?P<path>.*)', 'django.views.static.serve',
             {'document_root' : os.path.dirname(__file__) + '/static'} ),
    )

src/entries/models.py
# -*- encoding: utf-8 -*-

#=====================================================
# @file  :
# @brief :
#=====================================================

#--------- import ---------
from django.db import models
from django.forms import ModelForm

#------------------------------------------------
# @class : Entry
# @brief :
#------------------------------------------------
class Entry(models.Model):

    userid  = models.IntegerField()

    title   = models.CharField(max_length = 100)
    body    = models.TextField(max_length = 1000)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/entries/detail/%i" % self.id

class EntryForm(ModelForm):

    class Meta:
        model = Entry

src/entries/forms.py
# -*- encoding: utf-8 -*-

#=====================================================
# @file  :
# @brief :
#=====================================================

#--------- import ---------
from django import newforms as forms

#------------------------------------------------
# @class : UserRegistrationForm
# @brief : ユーザー登録用フォーム
#------------------------------------------------
class UserRegistrationForm( forms.Form ):

    #
    username = forms.CharField(
        required = True,
        max_length = 30,
        label = 'UserName' )

    #
    password = forms.CharField(
        required = True,
        max_length = 128,
        widget = forms.PasswordInput )

    #
    email = forms.EmailField(
        required = True,
        label = 'email address' )

# End of File

entries/views.py
# -*- coding: utf-8 -*-

#--------- import ---------
from django.shortcuts import render_to_response
from models import Entry, EntryForm

def page_list( request, object_id ):

    list = None

    try:
        list = Entry.objects.filter(userid=request.user.id)
    except Entry.DoesNotExist:
        list = []

    return render_to_response("entries/entry_list.html", {'request': request, 'object_list': list});


def create_entry( request ):

    if request.method == 'POST':
        new_data = request.POST.copy()
        form = EntryForm(new_data)

        if form.is_valid():
            form.userid = request.user.id
            obj = form.save()

            return HttpResponseRedirect( obj.get_absolute_url() )
    else:
        form = EntryForm()

    form = dict(form=form)

    return render_to_response( 'entries/entry_form.html', form )

src/entries/views.py
# -*- coding: utf-8 -*-

#--------- import ---------
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from src.entries.models import Entry, EntryForm

#--------- template ---------
template_path = 'entries/'

def page_list( request, object_id ):

    list = None

    try:
        list = Entry.objects.filter(userid=request.user.id)
    except Entry.DoesNotExist:
        list = []


    ctxt = RequestContext( request, {'request': request, 'object_list': list} )

    return render_to_response( template_path + "entry_list.html", ctxt)


def create_entry( request ):

    if request.method == 'POST':
        new_data = request.POST.copy()
        new_data['userid'] = request.user.id

        form = EntryForm(new_data)

        if form.is_valid():
            obj = form.save()

            return HttpResponseRedirect( obj.get_absolute_url() )
    else:
        form = EntryForm()

    form = dict(form=form)

    ctxt = RequestContext( request, form )

    return render_to_response( template_path + 'entry_form.html', ctxt )

templates/entries/base.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="ja" lang="ja">

<!-- header -->
<head>
    <meta http-equiv="Content-Type"
          content="text/html; charset=utf-8"/>
    <title>Entries</title>

    <meta http-equiv="content-language" content="ja"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta http-equiv="content-style-type" content="text/css"/>
    <meta http-equiv="content-script-type" content="text/javascript"/>

    <!-- css -->
    <link rel="stylesheet" type="text/css"
          href="{{ STATIC_URL }}css/stylesheet.css" media="all"/>

</head>

<!-- content -->
<body>
<div id="wrapper">
    <ul id="nav">
        <a href="/top/">top</a></li>
    </ul>
    <div id="header">
        <h1>mysite</h1>
    </div>

    <div id="main">

        {% block entries %} {% endblock %}
        {% block main %} {% endblock %}

    </div>
</body>
</html>



templates/entries/entry_add.html
{% include 'account/auth.html' %}

{% if not user.is_anonymous %}
    <dd div class="operation">
        <a href= "/entries/create/">記事の追加</a>
    </dd><hr/>
{% endif %}

{% block entry_content %}
{% endblock entry_content %}

templates/entries/entry_confirm_delete.html
{% extends "./base.html" %}

{% block content %}

<form method="post" action=".">

    <dt>
        タイトル: {{ object.title }}  <br/>
        コメント: {{ object.content}} <br/>
    </dt><br/>

    <p>この項目を削除します。よろしいですか？</p><br/>

    <input type="submit"/>
    <input type="button" value="いいえ" onClick="location.href='/entries/'" />
</form><br/>

<div class="operation">
    <a href="/entries/">一覧に戻る</a>
</div>

{% endblock %}

templates/entries/entry_detail.html
{% extends "./base.html" %}

{% load comments %}

{% block content %}

    <dt>
        タイトル: {{ object.title }} <br/>
        本文: {{ object.body }} <br/>
    </dt>

    <br/>

    <dd class="operation">
        <a href="/entries/update/{{ object.id }}">編集</a>
        <a href="/entries/delete/{{ object.id }}">削除</a>
        <a href="/entries/page/1/">一覧に戻る</a>
    </dd>

    <hr/>

    {% get_comment_list for object as comment_list %}
    {% for comment in comment_list %}
        {{ comment.user_name }}  <br/>
        {{ comment.submit_date }}  <br/>
        {{ comment.comment }} <br/>
        <br/>
    {% endfor %}

    <br/><hr/>

    {% render_comment_form for object %}

    <hr/>

{% endblock %}

templates/entries/entry_form.html
{% extends "./base.html" %}

{% block content %}

{% if object %}
    <h3>編集</h3><br/>
{% else %}
    <h3>新規作成</h3><br/>
{% endif %}

{% if form.has_errors %}
    {% for field in form.fields %}
        {% if field.error %}
            {{ field.error }}
        {% endif %}

    {% endfor %}
{% endif %}

<div class="validation">
    <form action="." method="post" accept-charset="utf-8">
        <label for="id_title">タイトル</label>{{ form.title }}
        {% if form.title.errors %} <p><error> {{ form.title.errors|join:", "}}</error></p>{% endif %}<br/><br/>
        <label for="id_body">内容</label>{{ form.body }}
        {% if form.body.errors %} <p><error>  {{ form.body.errors|join:", "}}</error></p><br/><br/>{% endif %}

{#        <label for="id_userid">内容</label>{{ form.userid }}#}
{#        {% if form.userid.errors %} <p><error>  {{ form.userid.errors|join:", "}}</error></p><br/><br/>{% endif %}#}

        <p><input type="submit" value="保存" /></p><br/>
    </form>
</div>


<div class="operation">
    <a href="/entries/page/1/">一覧に戻る</a>
</div>

{% endblock %}

templates/entries/entry_list.html
{% extends "./base.html" %}

{% block content %}

    <h3>一覧</h3>

    {% include 'entries/entry_add.html' %}

    {% for entry in object_list %}

        <dt>
            <a href="/entries/detail/{{ entry.id }}">{{ entry.title }}</a>
        </dt>

        <dd>
            {{ entry.content }}
        </dd><br/>

        <dd class="operation">
            <a href="/entries/update/{{ entry.id }}">編集</a>
            <a href="/entries/delete/{{ entry.id }}">削除</a>
        </dd>
        <hr/>

    {% endfor %}

{% endblock %}